image: docker:18-git
services:
  - docker:18-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - deploy

build:
  stage: build
  image: docker:stable-git
  script:
    - git submodule update --init --recursive
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN reg.g.hu.md
    - docker build -t reg.g.hu.md/hugo/cmyk .
    - docker tag reg.g.hu.md/hugo/cmyk reg.g.hu.md/hugo/cmyk:latest
    - docker tag reg.g.hu.md/hugo/cmyk reg.g.hu.md/hugo/cmyk:${CI_COMMIT_SHA:0:8}
    - docker push reg.g.hu.md/hugo/cmyk

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHA:0:8}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
