apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmyk
  namespace: cmyk
spec:
  selector:
    matchLabels:
      app: cmyk
  replicas: 1
  template:
    metadata:
      labels:
        app: cmyk
    spec:
      imagePullSecrets:
      - name: github-registry
      containers:
        - name: cmyk
          image: ghcr.io/hugomd/cmyk/cmyk:<VERSION>
          env:
            - name: DISCORD_TOKEN
              value: "<DISCORD_TOKEN>"
