apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmyk
  namespace: cmyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cmyk
    spec:
      imagePullSecrets:
      - name: github-registry
      containers:
        - name: cmyk
          image: docker.pkg.github.com/hugomd/cmyk/cmyk:<VERSION>
          env:
            - name: DISCORD_TOKEN
              value: "<DISCORD_TOKEN>"
