apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmyk
  namespace: cmyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cmyk
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cmyk
          image: reg.g.hu.md/hugo/cmyk:<VERSION>
          env:
            - name: DISCORD_TOKEN
              value: "<DISCORD_TOKEN>"
